core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from news import views

app_name = "news"
urlpatterns = [
    path("", views.horizon_press_home),
    path("<str:slug>", views.horizon_press_home, name="news_by_category"),
    path("submit_news/<str:slug>", views.submit_news, name="submit_news"),

    path('news_export/<int:category_id>/', views.news_export, name="news_export"),
    path('news_export/', views.news_export, name="news_export"),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError

from uuid import uuid4


# Create your models here.
class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Categories(Base):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    name = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if Categories.objects.filter(name__icontains=self.name).exists():
            raise ValidationError("Category already exist!")
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class News(Base):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)

    sentence = models.TextField()
    label = models.CharField(max_length=50)
    score = models.FloatField()
    transformers_result_dict = models.JSONField()  # for debugging purpose


def get_news_export_upload_to(instance, filename):
    category_name = "All" if not instance.category else str(instance.category.name).capitalize()
    return f'NewsExport/{category_name}/{filename}'


class NewsExports(Base):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, blank=True, null=True)
    file = models.FileField(upload_to=get_news_export_upload_to)

news/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

from common.utils import get_sentence_sentiment, handle_news_export
from .models import News, Categories


# Create your views here.
def horizon_press_home(request, slug=None):
    context = {
        "news": None,
        "category_selected": None,
    }
    news = News.objects.order_by("-id")

    if slug:
        category = Categories.objects.get(slug=slug)
        news = news.filter(category=category).order_by("-id")
        context["category_selected"] = category

    paginator = Paginator(news, 6)  # Show 25 contacts per page.

    page_number = request.GET.get("page", 1)
    paginated_news = paginator.get_page(page_number)
    context["news"] = paginated_news

    return render(request, "news/news.html", context)


def submit_news(request, slug):
    try:
        if request.method == "POST":
            if Categories.objects.count() < 5:
                raise Exception("Minimum 5 Categories required!")
            sentence = request.POST.get("sentence", None)
            if sentence:
                category = Categories.objects.get(slug=slug)
                result, pred, err_msg = get_sentence_sentiment(sentence)
                if result and pred:
                    created = News.objects.create(
                        category=category,
                        sentence=sentence,
                        label=pred["label"].lower(),
                        score=pred["score"],
                        transformers_result_dict=pred
                    )
                    if created:
                        messages.success(request, "Created!")
                    else:
                        raise Exception("Failed!")
                else:
                    raise Exception(err_msg if err_msg else "unable to find sentiment!")

    except Exception as err:
        messages.add_message(request, messages.ERROR, str(err), extra_tags='danger')

    return redirect("news:news_by_category", slug=slug)


@csrf_exempt
def news_export(request, category_id=None):
    response = {"status": 200, "file": None}
    try:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest' and request.method == "POST":
            url = handle_news_export(category_id)
            if url:
                response["file"] = url
        else:
            raise Exception("Not an ajax request!")
    except Exception as err:
        response["status"] = 400
        response["message"] = str(err)
    return JsonResponse(response, status=response["status"])

news/templates/news/base.html
<!DOCTYPE html>
{% load static %}
{% load news_template_tags %}
{% load_categories_nav %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HorizonPress</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'news/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'news/assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'news/assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'news/assets/images/favicon.ico' %}" />
    <style>
      .brand-logo , .brand-logo-mini{
        background: linear-gradient(45deg, #ff8a00, #e52e71) !important;
        -webkit-background-clip: text !important;
        color: transparent !important;
      }
    </style>
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">

          <a class="navbar-brand brand-logo" href="/"><h2>HorizonPress</h2></a>
          <a class="navbar-brand brand-logo-mini" href="/"><h2>HP</h2></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
              <div class="input-group">
                <div class="input-group-prepend bg-transparent">
                  <i class="input-group-text border-0 mdi mdi-magnify"></i>
                </div>
                <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
              </div>
            </form>
          </div>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Categories / Labels</span>
                <i class="menu-arrow"></i>
              </a>
              <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                  {% for category in categories_navigations %}
                  <li class="nav-item"> <a class="nav-link" href="{% url 'news:news_by_category' slug=category.slug %}">{{category.name | title}}</a></li>
                  {% endfor %}
                </ul>
              </div>
            </li>
          </ul>
        </nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'news/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'news/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'news/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'news/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'news/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'news/assets/js/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'news/assets/js/dashboard.js' %}"></script>
    <script src="{% static 'news/assets/js/todolist.js' %}"></script>
    <!-- End custom js for this page -->
  {% block script %}
  {% endblock script %}
  </body>
</html>

news/templates/news/news.html
{%  extends 'news/base.html' %}
{% block content %}
<div class="page-header">
    <h3 class="page-title">
    <span class="page-title-icon bg-gradient-primary text-white me-2">
      <i class="mdi mdi-newspaper"></i>
    </span>{% if category_selected %} News - {{category_selected.name | title}}{% else %}All News{% endif %}
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <button id="export" class="btn btn-gradient-danger btn-icon-text" data-exportUrl="{% if category_selected %}{% url 'news:news_export' category_id=category_selected.id %}{% else %}{% url 'news:news_export' %}{% endif %}"><i class="mdi mdi-cloud-download"></i> Export
                </button>
            </li>
        </ul>
    </nav>
</div>
<div class="row">
    {% for data in news %}
    <div class="col-md-4 grid-margin stretch-card">
        <div class="card">
            <div class="card-body pb-0">
                <h4 class="card-title">{% if not category_selected %}{{data.category.name | title}}{% endif %}</h4>
            </div>
            <div class="card-body">
                <blockquote class="mb-0 blockquote blockquote-primary" style="border-radius : 5px; border-color :
                                           {% if data.label == 'positive' or data.label == 'very positive' %}
                                            #198754
                                           {% elif data.label == 'negative' or data.label == 'very negative'%}
                                           #dc3545
                                           {% elif data.label == 'neutral' %}
                                           #9da5b1
                                           {% endif %}
                                           ">
                    <p>{{data.sentence}}</p>
                    <footer class="blockquote-footer" style="color :
                                           {% if data.label == 'positive' or data.label == 'very positive' %}
                                            #198754
                                           {% elif data.label == 'negative' or data.label == 'very negative'%}
                                           #dc3545
                                           {% elif data.label == 'neutral' %}
                                           #9da5b1
                                           {% endif %}
                                           ">
                        <i> label : {{data.label |upper }} | <cite title="Source Title"> score : {{data.score}}</cite></i>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
    {% empty %}
    <i>News not found!</i>
    {% endfor %}
    <div>
        <nav aria-label="...">
          <ul class="pagination justify-content-end">

            <li class="page-item">
              <a class="page-link" href="?page=1">First</a>
            </li>

            <li class="page-item {% if not news.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if news.has_previous %}?page={{ news.previous_page_number }}{% endif %}">Previous</a>
            </li>

            <li class="page-item active" aria-current="page">
              <a class="page-link" href="#">Page {{ news.number }} of {{ news.paginator.num_pages }}</a>
            </li>

            <li class="page-item {% if not news.has_next %}disabled{% endif %}">
              <a class="page-link" href="{% if news.has_next %}?page={{ news.next_page_number }}{% endif %}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ news.paginator.num_pages }}">Last</a>
            </li>
          </ul>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body p-2">
            {% if messages %}
              {% for message in messages %}
                {% if message.tags %}
                  <div role="alert" class="alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>
                {% endif %}
              {% endfor %}
            {% endif %}

            {% if category_selected %}
            <form method="POST" action="{% url 'news:submit_news' slug=category_selected.slug %}" class="w-100">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 d-flex" style="justify-content: space-between;">
                       <textarea class="form-control" name="sentence" placeholder="Sentence" style="width:85%"></textarea>
                       <button class="btn btn-gradient-primary me-2">Submit</button>
                    </div>
                </div>
            </form>
            {% else %}
            <i>Please choose category or label from the navigation to submit sentences.</i>
            {% endif %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $("#export").click(function(e) {
      e.preventDefault();

      const exportUrl = $(this).attr("data-exportUrl")
      console.log(exportUrl);

      $.ajax({
          type: "POST",
          url: exportUrl,
          data: {},
          contentType: 'application/json',
          success: function (data) {
            console.log("data",data);
            if (data.status === 200){
                window.location.href = data.file;
            }else{
            alert("Something went wrong")
            }
          },
          error: function(error){
            console.error(error);
          },
        });

    });
</script>
{% endblock script %}